var cheers = {
  'en': [
    '''You're stronger than you think!''',
    '''Take a deep breath, and remember that you've got this.''',
    '''Life is full of challenges, but you're capable of overcoming them.''',
    '''Every day is a new opportunity to make things better.''',
    '''Believe in yourself and your abilities.''',
    '''Keep your head high, and keep moving forward.''',
    '''Smile – it looks good on you!''',
    '''Your potential is limitless.''',
    '''Embrace the beauty of each new day.''',
    '''Positive thoughts lead to positive outcomes.''',
    '''You're a shining star in your own story.''',
    '''Don't forget to treat yourself with kindness.''',
    '''Small steps can lead to big changes.''',
    '''Brighten someone's day with your positivity.''',
    '''A positive attitude can make a world of difference.''',
    '''You're one in a million – truly unique!''',
    '''Life is an adventure waiting for you.''',
    '''Good things are on the horizon.''',
    '''Don't let a bad day define you.''',
    '''Inhale courage, exhale fear.''',
    '''Your presence makes the world a better place.''',
    '''Celebrate your successes, no matter how small.''',
    '''You're capable of achieving greatness.''',
    '''Keep the faith, and keep going.''',
    '''Your smile can light up the darkest days.''',
    '''Every challenge is an opportunity for growth.''',
    '''You're making progress, even if it doesn't feel like it.''',
    '''Your dreams are worth pursuing.''',
    '''Take a moment to appreciate how far you've come.''',
    '''Life's hurdles are stepping stones to success.''',
    '''Remember, setbacks are setups for comebacks.''',
    '''You have the power to turn things around.''',
    '''You're a magnet for all things good.''',
    '''The world is a better place with you in it.''',
    '''Your potential knows no bounds.''',
    '''Don't be afraid to ask for help when you need it.''',
    '''Your inner strength is your greatest asset.''',
    '''Believe in your journey, even when it's tough.''',
    '''You're writing your own success story.''',
    '''Your smile can change the world for someone.''',
    '''You're a masterpiece in progress.''',
    '''Stay positive, stay fighting, and stay brave.''',
    '''You're a force to be reckoned with.''',
    '''Dream big and dare to chase those dreams.''',
    '''Even on cloudy days, find your own sunshine.''',
    '''You've got an incredible journey ahead.''',
    '''Your potential is as vast as the ocean.''',
    '''Challenges are opportunities in disguise.''',
    '''The best is yet to come.''',
    '''Every day is a chance to begin anew.''',
    '''Believe in yourself, and others will too.''',
    '''Your happiness is worth fighting for.''',
    '''You're on the path to something amazing.''',
    '''Stay focused on your goals, and you'll achieve them.''',
    '''You are loved and appreciated.''',
    '''Your journey is uniquely yours – embrace it.''',
    '''Strength comes from overcoming adversity.''',
    '''Today is a gift; that's why it's called the present.''',
    '''You're a resilient, beautiful soul.''',
    '''Don't let self-doubt hold you back.''',
    '''Your determination is inspiring.''',
    '''The world is full of possibilities.''',
    '''Small steps today lead to big leaps tomorrow.''',
    '''You're a source of positivity and light.''',
    '''You are enough, just as you are.''',
    '''Even in the toughest times, you shine.''',
    '''You have the power to shape your destiny.''',
    '''Success is the sum of small efforts repeated day in and day out.''',
    '''Your potential is like a treasure waiting to be discovered.''',
    '''Trust in the magic of new beginnings.''',
    '''No one can dull your sparkle.''',
    '''Embrace each day with an open heart.''',
    '''Your journey is full of promise.''',
    '''Difficult roads often lead to beautiful destinations.''',
    '''Celebrate your uniqueness – it's your superpower.''',
    '''Your journey may have challenges, but it's worth it.''',
    '''You're on the brink of something incredible.''',
    '''You have the courage to face any obstacle.''',
    '''You're not alone; we're here to support you.''',
    '''Your smile is a ray of sunshine in someone's day.''',
    '''You are a beacon of hope and inspiration.''',
    '''Believe in your ability to overcome.''',
    '''Success begins with a single step – take it.''',
    '''You're a bright star in the night sky.''',
    '''Your positivity is contagious.''',
    '''You are loved and cherished.''',
    '''The world is a canvas, and you're the artist.''',
    '''Your strength lies in your resilience.''',
    '''Stay focused, stay determined, and stay hopeful.''',
    '''You're making a positive impact every day.''',
    '''You have the power to create the life you desire.''',
    '''Keep pushing through; great things are coming.''',
    '''You are a masterpiece in progress.''',
    '''Embrace change; it's the path to growth.''',
    '''Your heart is a wellspring of kindness.''',
    '''Believe in your ability to overcome anything.''',
    '''You are capable of achieving your dreams.''',
    '''Your journey is filled with promise and potential.''',
    '''You're an inspiration to those around you.''',
    '''Keep going, keep growing, and keep shining.''',
  ],
  'ru': [
    '''Вы сильнее, чем вам кажется!''',
    '''Сделайте глубокий вдох и вспомните, что у вас все получится.''',
    '''Жизнь полна трудностей, но вы способны их преодолеть.''',
    '''Каждый день - это новая возможность сделать все лучше.''',
    '''Верьте в себя и свои возможности.''',
    '''Держите голову высоко и двигайтесь вперед.''',
    '''Улыбайтесь - вам это идет!''',
    '''Ваш потенциал безграничен.''',
    '''Примите красоту каждого нового дня.''',
    '''Позитивные мысли приводят к позитивным результатам.''',
    '''Вы - сияющая звезда в своей собственной истории.''',
    '''Не забывайте относиться к себе с добротой.''',
    '''Маленькие шаги могут привести к большим переменам.''',
    '''Украсьте чей-то день своим позитивом.''',
    '''Позитивный настрой может изменить мир к лучшему.''',
    '''Вы один на миллион - поистине уникальны!''',
    '''Жизнь - это приключение, которое ждет вас.''',
    '''Хорошие события не за горами.''',
    '''Не позволяйте плохому дню определять вас.''',
    '''Вдыхайте мужество, выдыхайте страх.''',
    '''Ваше присутствие делает мир лучше.''',
    '''Празднуйте свои успехи, какими бы маленькими они ни были.''',
    '''Вы способны достичь величия.''',
    '''Сохраняйте веру и продолжайте идти вперед.''',
    '''Ваша улыбка способна осветить самые мрачные дни.''',
    '''Любая трудность - это возможность для роста.''',
    '''Вы добиваетесь прогресса, даже если вам этого не кажется.''',
    '''Ваши мечты стоят того, чтобы к ним стремиться.''',
    '''Найдите время, чтобы оценить, как далеко вы продвинулись.''',
    '''Жизненные препятствия - это ступеньки к успеху.''',
    '''Помните, что неудачи - это повод для возвращения.''',
    '''У вас есть возможность повернуть все вспять.''',
    '''Вы - магнит для всего хорошего.''',
    '''Мир становится лучше, когда в нем есть Вы.''',
    '''Ваш потенциал не знает границ.''',
    '''Не бойтесь просить о помощи, когда она вам нужна.''',
    '''Ваша внутренняя сила - ваше главное богатство.''',
    '''Верьте в свой путь, даже если он труден.''',
    '''Вы сами пишете свою историю успеха.''',
    '''Ваша улыбка может изменить мир для кого-то.''',
    '''Вы - шедевр в процессе работы.''',
    '''Оставайтесь позитивными, боритесь и будьте храбрыми.''',
    '''Вы - сила, с которой нужно считаться.''',
    '''Мечтайте о многом и смело преследуйте эти мечты.''',
    '''Даже в пасмурные дни находите свой собственный солнечный свет.''',
    '''Впереди у вас невероятное путешествие.''',
    '''Ваш потенциал огромен, как океан.''',
    '''Трудности - это замаскированные возможности.''',
    '''Лучшее еще впереди.''',
    '''Каждый день - это шанс начать все заново.''',
    '''Поверьте в себя, и другие тоже поверят.''',
    '''Ваше счастье стоит того, чтобы за него бороться.''',
    '''Вы находитесь на пути к чему-то удивительному.''',
    '''Сосредоточьтесь на своих целях, и вы их достигнете.''',
    '''Вас любят и ценят.''',
    '''Ваш путь уникален - примите его.''',
    '''Сила приходит через преодоление трудностей.''',
    '''Сегодняшний день - это подарок, поэтому он и называется настоящим.''',
    '''Вы - стойкая, прекрасная душа.''',
    '''Не позволяйте неуверенности в себе сдерживать вас.''',
    '''Ваша решимость вдохновляет.''',
    '''Мир полон возможностей.''',
    '''Маленькие шаги сегодня приводят к большим скачкам завтра.''',
    '''Вы - источник позитива и света.''',
    '''Вас достаточно, такой, какая вы есть.''',
    '''Даже в самые трудные времена вы сияете.''',
    '''Вы способны определять свою судьбу.''',
    '''Успех - это сумма небольших усилий, повторяющихся изо дня в день.''',
    '''Ваш потенциал подобен сокровищу, которое ждет, когда его откроют.''',
    '''Верьте в магию новых начинаний.''',
    '''Никто не сможет притушить ваше сияние.''',
    '''Принимайте каждый день с открытым сердцем.''',
    '''Ваш путь полон надежд.''',
    '''Трудные дороги часто приводят к прекрасным местам.''',
    '''Отмечайте свою уникальность - это ваша суперсила.''',
    '''Ваш путь может быть сопряжен с трудностями, но он того стоит.''',
    '''Вы стоите на пороге чего-то невероятного.''',
    '''У вас хватит мужества преодолеть любые препятствия.''',
    '''Вы не одиноки; мы здесь, чтобы поддержать вас.''',
    '''Ваша улыбка - это луч солнца в чьем-то дне.''',
    '''Вы - маяк надежды и вдохновения.''',
    '''Верьте в свою способность преодолеть трудности.''',
    '''Успех начинается с одного шага - сделайте его.''',
    '''Вы - яркая звезда на ночном небе.''',
    '''Ваша позитивность заразительна.''',
    '''Вас любят и лелеют.''',
    '''Мир - это холст, а вы - художник.''',
    '''Ваша сила - в вашей стойкости.''',
    '''Оставайтесь сосредоточенными, целеустремленными и не теряйте надежды.''',
    '''Каждый день вы оказываете положительное влияние.''',
    '''В ваших силах создать ту жизнь, которую вы хотите.''',
    '''Не останавливайтесь на достигнутом; великие дела не за горами.''',
    '''Вы - шедевр в процессе работы.''',
    '''Примите перемены - это путь к росту.''',
    '''Ваше сердце - источник доброты.''',
    '''Верьте в свою способность преодолеть все.''',
    '''Вы способны достичь своей мечты.''',
    '''Ваш путь полон перспектив и потенциала.''',
    '''Вы вдохновляете окружающих.''',
    '''Продолжайте идти вперед, расти и сиять.''',
  ],
};

var progress = {
  'en': [
    '''You've got this! Even when the path seems tough, remember that every small step forward is a victory. Keep pushing forward, and the journey will become easier.''',
    '''Life is a journey filled with ups and downs, but it's in those moments of challenge that you discover your true strength. Don't be disheartened; you're closer to success than you realize.''',
    '''In the face of adversity, your resilience shines brightly. You have the power to overcome obstacles and achieve greatness. Believe in yourself and your abilities.''',
    '''Cherish every step you take, no matter how small. Each one brings you closer to your goals. Your journey is uniquely yours, and it's something to be proud of.''',
    '''Stay focused and remain determined. With each sunrise, you have a new chance to make progress. Every day is an opportunity to come closer to your dreams.''',
    '''Life's challenges are like stepping stones to your success. Embrace them, learn from them, and use them to propel yourself forward. Your dreams are within reach.''',
    '''The road to success may have its twists and turns, but each one is a valuable lesson in your journey. Stay patient, and you'll find the way.''',
    '''Your potential knows no bounds. You have the capacity to achieve greatness and accomplish your dreams. Keep moving forward, one step at a time.''',
    '''Don't let setbacks discourage you. They're not the end of the road; they're merely detours on your path to success. Stay resilient and keep your vision clear.''',
    '''Every day is a fresh opportunity to begin anew. Embrace the challenges, for they are what make your victories all the more sweet. You're on a remarkable journey, and the best is yet to come.''',
    '''The greatest of achievements often arise from the toughest of trials. Your resilience and determination are your secret weapons for success. Keep fighting for what you want.''',
    '''Success isn't about achieving everything at once. It's about the steady progress you make each day. Celebrate your small victories; they are building the foundation for your dreams.''',
    '''Your journey is uniquely yours. Embrace it, for every twist and turn has a purpose. Your experiences are shaping you into someone extraordinary.''',
    '''Your determination is inspiring. Don't lose sight of your dreams; they are within your reach. Keep your vision clear, and the path to success will open before you.''',
    '''Even on the cloudiest days, find your own sunshine. Your positive outlook and resilience are like rays of hope that can brighten the darkest moments.''',
    '''You are enough, just as you are. Remember that you have the power within you to overcome any challenge that comes your way. Keep moving forward, and success will follow.''',
    '''You have the courage to face any obstacle. Let that inner strength guide you through challenges, and remember that every difficulty is a stepping stone to your goals.''',
    '''Your journey may have challenges, but it's worth it. The path to success is not always easy, but with each hurdle, you grow stronger and wiser. Keep going, and you'll reach your destination.''',
    '''Your dreams are worth pursuing, and every step you take brings you closer to them. So, keep pursuing your goals with unwavering determination, for success is on the horizon.''',
    '''You have the power to shape your destiny. Each decision you make, each step you take, is a brushstroke on the canvas of your life. Paint a masterpiece that's uniquely yours.''',
    '''Stay focused on your goals and stay committed to your journey. You're on the right path, and every challenge you face is simply a test of your determination.''',
    '''You are making a positive impact every day, even if it doesn't always feel like it. Your presence and perseverance matter, and they're making a difference in the world.''',
    '''Your smile is like a beacon of hope that can light up the darkest moments. Keep shining, because your light has the power to inspire and uplift those around you.''',
    '''Believe in your ability to overcome anything. Your strength, resilience, and determination are your allies on the path to success. Keep pushing forward, and you'll reach your goals.''',
    '''Your journey has been filled with challenges, but they've only made you stronger. Now, as you face each day with determination, remember that your future holds the promise of victory. Success is within your grasp, and you're well on your way to achieving it. Keep the faith and keep moving forward, because the best is yet to come.'''
  ],
  'ru': [
    '''Вы справитесь! Даже если путь кажется трудным, помните, что каждый маленький шаг вперед - это победа. Продолжайте двигаться вперед, и путь станет легче.''',
    '''Жизнь - это путешествие, полное взлетов и падений, но именно в моменты испытаний вы обнаруживаете свою истинную силу. Не падайте духом: вы ближе к успеху, чем думаете.''',
    '''Перед лицом невзгод ваша стойкость ярко проявляется. У вас есть силы преодолеть препятствия и достичь величия. Верьте в себя и свои способности.''',
    '''Дорожите каждым своим шагом, каким бы маленьким он ни был. Каждый из них приближает вас к цели. Ваш путь уникален, и это повод для гордости.''',
    '''Оставайтесь сосредоточенными и целеустремленными. С каждым восходом солнца у вас появляется новый шанс добиться успеха. Каждый день - это возможность приблизиться к своей мечте.''',
    '''Жизненные трудности - это ступеньки на пути к успеху. Примите их, учитесь на них и используйте для движения вперед. Ваши мечты достижимы.''',
    '''Дорога к успеху может иметь свои повороты и изгибы, но каждый из них - это ценный урок на вашем пути. Наберитесь терпения, и вы найдете дорогу.''',
    '''Ваш потенциал не знает границ. Вы способны достичь величия и осуществить свои мечты. Продолжайте двигаться вперед, делая один шаг за другим.''',
    '''Не позволяйте неудачам обескуражить Вас. Это не конец пути, а лишь препятствия на пути к успеху. Сохраняйте стойкость и ясность видения.''',
    '''Каждый день - это новая возможность начать все заново. Принимайте трудности, ведь именно они делают ваши победы еще более приятными. Вы находитесь на удивительном пути, и лучшее еще впереди.''',
    '''Самые великие достижения часто рождаются из самых тяжелых испытаний. Ваша стойкость и целеустремленность - ваше секретное оружие для достижения успеха. Продолжайте бороться за то, чего вы хотите.''',
    '''Успех заключается не в том, чтобы достичь всего и сразу. Успех - это постоянное продвижение вперед каждый день. Радуйтесь своим маленьким победам - они закладывают фундамент вашей мечты.''',
    '''Ваш путь уникален. Примите его, ведь каждый поворот имеет свою цель. Ваш опыт формирует из вас необыкновенного человека.''',
    '''Ваша решимость вдохновляет. Не теряйте из виду свои мечты - они в пределах вашей досягаемости. Сохраняйте ясность видения, и путь к успеху откроется перед вами.''',
    '''Даже в самые пасмурные дни находите в себе солнечный свет. Ваше позитивное мировоззрение и стойкость подобны лучам надежды, способным скрасить самые мрачные моменты.''',
    '''Вы достаточны, такие, какие вы есть. Помните, что в вас есть сила, способная преодолеть любые трудности, возникающие на вашем пути. Продолжайте двигаться вперед, и успех обязательно придет.''',
    '''У вас есть мужество, чтобы противостоять любым препятствиям. Пусть эта внутренняя сила поможет вам справиться с трудностями, и помните, что любая трудность - это ступенька к достижению цели.''',
    '''Ваш путь может быть сопряжен с трудностями, но он того стоит. Путь к успеху не всегда прост, но с каждым препятствием вы становитесь сильнее и мудрее. Продолжайте идти вперед, и вы достигнете своей цели.''',
    '''Ваши мечты стоят того, чтобы к ним стремиться, и каждый ваш шаг приближает вас к ним. Так что продолжайте идти к своей цели с непоколебимой решимостью, и успех не за горами.''',
    '''В ваших силах определить свою судьбу. Каждое решение, каждый шаг - это мазок кисти на холсте вашей жизни. Нарисуйте шедевр, который будет принадлежать только вам.''',
    '''Сосредоточьтесь на своих целях и продолжайте свой путь. Вы на правильном пути, и каждое испытание, с которым вы сталкиваетесь, - это просто проверка вашей решимости.''',
    '''Каждый день вы оказываете положительное влияние на ситуацию, даже если это не всегда ощущается. Ваше присутствие и настойчивость имеют значение, и они меняют мир к лучшему.''',
    '''Ваша улыбка подобна маяку надежды, способному осветить самые мрачные моменты. Продолжайте светить, потому что ваш свет способен вдохновлять и поднимать настроение окружающим.''',
    '''Верьте в свою способность преодолеть все. Ваша сила, стойкость и решительность - ваши союзники на пути к успеху. Продолжайте двигаться вперед, и вы достигнете своих целей.''',
    '''Ваш путь был полон трудностей, но они сделали вас только сильнее. Теперь, решительно встречая каждый день, помните, что ваше будущее обещает вам победу. Успех не за горами, и вы уже на пути к нему. Сохраняйте веру и двигайтесь вперед, ведь лучшее еще впереди''',
  ]
};

var stab = '[%%]';

var reportPart0 = {
  'en': [
    '''It's evident that the triggers you're facing, with an average power of [%%] can be quite formidable. Understanding this intensity is a significant step in your journey to overcome addiction.''',
    '''The strength of the triggers, averaging at [%%] underscores the gravity of your situation. This knowledge is essential for developing effective coping strategies.''',
    '''Coping with addiction can be incredibly challenging, particularly when dealing with triggers that carry an average power of [%%] Your awareness of this intensity is a crucial aspect of your journey.''',
    '''Your recognition of triggers with an average power of [%%] is a vital part of your self-awareness. This information will help you develop strategies to combat these strong cravings effectively.''',
    '''Understanding that your triggers have an average power of [%%] is a significant step towards better managing your addiction. It's essential to address this level of intensity in your recovery process.''',
    '''The power level of your triggers, averaging at [%%] highlights the need for resilience and a solid support system. Stay committed to your journey to overcome addiction.''',
    '''Overcoming addiction is a journey filled with ups and downs. The fact that your triggers have an average power of [%%] can guide you in tailoring your coping strategies effectively.''',
    '''The strength of your triggers, with an average power of [%%] is a clear indication of the challenges you face. Seek professional assistance and support to tackle this level of intensity.''',
    '''Coping with addiction can be demanding, especially when your triggers are rated at an average power of [%%] Your commitment to change is the key to success on this path.''',
    '''Your self-awareness about the potency of your triggers, averaging at [%%] is a significant part of your recovery journey. You're on the path to better managing these strong cravings.''',
    '''The intensity of your triggers, averaging at [%%] underscores the gravity of your situation. Keep reaching out for support and stay determined to overcome addiction.''',
    '''Your journey to quit addiction is marked by powerful triggers, averaging at [%%] in intensity. Continue exploring different coping mechanisms and strategies to tackle this level of intensity.''',
    '''Acknowledging the strength of your triggers, with an average power of [%%] is a crucial part of taking control of your addiction. Continue to learn and adapt to address these powerful cravings effectively.''',
    '''It's clear that the triggers you're dealing with carry significant weight, with an average power of [%%] This information provides valuable insights into the difficulties you're encountering.''',
    '''Coping with addiction can be particularly tough, especially when the average trigger power is [%%] Seek support and resources to help you navigate this challenging terrain and tackle this level of intensity.''',
    '''The triggers you're facing, with an average power of [%%] can be demanding. However, remember that you're not alone in this journey, and there is support available to help you manage these strong cravings.''',
    '''The average power level of your triggers, rated at [%%] highlights the gravity of your situation. Take this knowledge as motivation to build resilience and work towards overcoming addiction.''',
    '''Your determination to overcome addiction is inspiring, especially when dealing with triggers that have an average power of [%%] You have the capacity to confront this level of intensity and emerge victorious.''',
    '''Your resilience and determination will be crucial in facing triggers with an average power of [%%] Stay patient and committed as you work towards reducing this level of intensity in your cravings.''',
    '''Recognizing that your triggers have an average power of [%%] is a significant part of your self-awareness. Utilize this understanding to help you devise strategies to combat these strong cravings effectively.''',
    '''Coping with addiction, especially with triggers rated at an average power of [%%] requires determination and a strong support system. You're capable of taking on this challenge and successfully addressing this level of intensity.''',
    '''The triggers you're dealing with, rated at an average power of [%%] are formidable opponents. Your inner strength and the support of others will help you in tackling this level of intensity.''',
    '''Your journey may have challenges, especially when triggers average at [%%] in power. Stay committed to your recovery process and continue to explore different strategies to address this level of intensity.''',
    '''Coping with addiction can be incredibly tough, especially when dealing with triggers rated at an average power of [%%] This level of intensity is challenging, but you're not alone in your journey.''',
    '''It's essential to acknowledge that the triggers you're experiencing carry a considerable weight, with an average power of [%%] This knowledge can help you devise effective coping strategies to tackle this level of intensity.''',
  ],
  'ru': [
    '''Очевидно, что триггеры, с которыми вы сталкиваетесь, со средней силой [%%] могут быть весьма грозными. Понимание этой силы является важным шагом на пути преодоления зависимости.''',
    '''Сила триггеров, составляющая в среднем [%%], подчеркивает серьезность вашей ситуации. Это знание необходимо для разработки эффективных стратегий преодоления зависимости.''',
    '''Борьба с зависимостью может быть невероятно сложной, особенно когда приходится иметь дело с триггерами, средняя сила которых составляет [%%] Осознание этой силы - важнейший аспект вашего пути.''',
    '''Осознание триггеров со средней силой [%%] является важной частью вашего самоанализа. Эта информация поможет вам разработать стратегии эффективной борьбы с сильным влечением.''',
    '''Понимание того, что ваши триггеры имеют среднюю силу [%%], является важным шагом на пути к более эффективному управлению своей зависимостью. В процессе выздоровления очень важно учитывать этот уровень интенсивности.''',
    '''Уровень силы ваших триггеров, составляющий в среднем [%%], подчеркивает необходимость стойкости и надежной системы поддержки. Сохраняйте приверженность своему пути преодоления зависимости.''',
    '''Преодоление зависимости - это путь, полный взлетов и падений. Тот факт, что средняя сила ваших триггеров составляет [%%], может помочь вам подобрать эффективные стратегии преодоления зависимости.''',
    '''Сила ваших триггеров, средняя мощность которых составляет [%%], является четким указанием на трудности, с которыми вы сталкиваетесь. Чтобы справиться с таким уровнем интенсивности, обратитесь за профессиональной помощью и поддержкой.''',
    '''Борьба с зависимостью может быть очень сложной, особенно если ваши триггеры имеют среднюю силу [%%] Ваше стремление к изменениям - залог успеха на этом пути.''',
    '''Самоосознание силы своих триггеров, средняя мощность которых составляет [%%], является важной частью вашего пути к выздоровлению. Вы находитесь на пути к тому, чтобы лучше справляться с сильным влечением.''',
    '''Интенсивность Ваших триггеров, составляющая в среднем [%%], подчеркивает серьезность Вашей ситуации. Продолжайте обращаться за поддержкой и сохраняйте решимость преодолеть зависимость.''',
    '''Ваш путь к отказу от зависимости отмечен мощными триггерами, средняя интенсивность которых составляет [%%]. Продолжайте изучать различные механизмы преодоления и стратегии, чтобы справиться с этим уровнем интенсивности.''',
    '''Признание силы своих триггеров, средняя сила которых составляет [%%], является важнейшей составляющей контроля над своей зависимостью. Продолжайте учиться и адаптироваться, чтобы эффективно бороться с этими сильными влечениями.''',
    '''Очевидно, что триггеры, с которыми вы имеете дело, имеют значительный вес (средняя сила [%%]) Эта информация дает ценное представление о трудностях, с которыми вы сталкиваетесь.''',
    '''Борьба с зависимостью может быть особенно трудной, особенно если средняя сила триггеров составляет [%%] Обратитесь за поддержкой и ресурсами, которые помогут вам сориентироваться на этом сложном пути и справиться с таким уровнем интенсивности.''',
    '''Триггеры, с которыми вы сталкиваетесь, со средней силой [%%] могут быть очень сложными. Однако помните, что вы не одиноки в этом путешествии, и у вас есть поддержка, которая поможет вам справиться с сильным влечением.''',
    '''Средний уровень силы Ваших триггеров, оцениваемый в [%%], подчеркивает серьезность Вашей ситуации. Примите это знание как мотивацию для укрепления стойкости и работы над преодолением зависимости.''',
    '''Ваша решимость преодолеть зависимость вдохновляет, особенно когда вы имеете дело с триггерами, средняя сила которых составляет [%%] Вы способны противостоять такому уровню интенсивности и выйти победителем.''',
    '''Ваша стойкость и решимость будут иметь решающее значение в противостоянии триггерам со средней силой [%%] Сохраняйте терпение и самоотверженность, работая над снижением интенсивности влечений.''',
    '''Осознание того, что Ваши триггеры имеют среднюю силу [%%], является важной частью Вашего самоанализа. Используйте это понимание для разработки стратегий эффективной борьбы с сильными влечениями.''',
    '''Борьба с зависимостью, особенно с триггерами средней силы [%%], требует решимости и сильной системы поддержки. Вы способны принять этот вызов и успешно справиться с таким уровнем интенсивности.''',
    '''Триггеры, с которыми Вы имеете дело, со средней силой [%%], являются грозными противниками. Ваша внутренняя сила и поддержка окружающих помогут Вам справиться с этим уровнем интенсивности.''',
    '''На вашем пути могут возникнуть трудности, особенно если триггеры имеют среднюю силу [%%]. Сохраняйте приверженность процессу выздоровления и продолжайте изучать различные стратегии борьбы с этим уровнем интенсивности.''',
    '''Борьба с зависимостью может быть невероятно трудной, особенно когда приходится иметь дело с триггерами, средняя сила которых составляет [%%] Этот уровень интенсивности является сложным, но вы не одиноки в своем путешествии.''',
    '''Важно признать, что испытываемые вами триггеры имеют значительный вес, их средняя сила составляет [%%] Эти знания помогут вам разработать эффективные стратегии преодоления этого уровня интенсивности.''',
  ]
};

var reportPart1 = {
  'en': [
    '''[%%] is the most potent trigger for you, and it's essential to concentrate on managing it.''',
    '''Focusing on coping with [%%], your most influential trigger, is of utmost importance.''',
    '''To make progress, it's vital to address [%%], which is your most dominant trigger.''',
    '''You should prioritize handling [%%], as it's your most substantial trigger.''',
    '''Your primary trigger is [%%], and dedicating attention to it is crucial.''',
    '''In your journey, dealing with [%%], your most impactful trigger, is key.''',
    '''To succeed, you must work on confronting [%%], your most powerful trigger.''',
    '''Tackling [%%], your most significant trigger, should be your primary objective.''',
    '''Addressing [%%] is imperative, as it is your most profound trigger.''',
    '''[%%] is the trigger that holds the most sway; it should be your focus.''',
    '''Your journey will benefit greatly from addressing [%%], your most prominent trigger.''',
    '''The trigger [%%] has the most influence on you, so managing it is paramount.''',
    '''For effective progress, you must concentrate on [%%], your most critical trigger.''',
    '''Handling [%%], your most dominant trigger, is the key to your success.''',
    '''In your efforts, focusing on [%%], your most substantial trigger, is vital.''',
    '''Dealing with [%%] should be at the forefront of your efforts, as it's your most significant trigger.''',
    '''[%%], your primary trigger, requires special attention to manage effectively.''',
    '''To make headway, addressing [%%] is of the utmost importance as it's your most impactful trigger.''',
    '''Your path to recovery centers around [%%], your most powerful trigger.''',
    '''Managing [%%] is essential, as it's your most profound trigger.''',
    '''It's crucial to focus on [%%], the trigger that carries the most weight.''',
    '''To succeed in your journey, addressing [%%], your most prominent trigger, is key.''',
    '''Confronting [%%] is the pivotal step, as it's your most influential trigger.''',
    '''Addressing [%%], your most critical trigger, should be your primary goal.''',
    '''In your quest to overcome addiction, [%%] is the trigger that requires your utmost attention.''',
    '''Managing [%%], your most substantial trigger, is central to your journey.''',
    '''To achieve your goals, concentrating on [%%], your most dominant trigger, is essential.''',
    '''Working on [%%] is paramount, as it is your most significant trigger.''',
    '''Your success hinges on addressing [%%], the trigger with the most profound impact.''',
    '''[%%], your trigger of utmost importance, demands your dedicated efforts to manage effectively.''',
  ],
  'ru': [
    '''[%%] является для вас самым сильным триггером, и необходимо сосредоточиться на управлении им.''',
    '''Сосредоточиться на преодолении [%%], вашего самого влиятельного триггера, крайне важно.''',
    '''Для того чтобы добиться прогресса, крайне важно заняться [%%], который является вашим наиболее доминирующим триггером.''',
    '''Вы должны уделять первостепенное внимание работе с [%%], поскольку это ваш самый существенный триггер.''',
    '''Ваш основной триггер - [%%], и уделять ему внимание крайне важно.''',
    '''В вашем путешествии работа с [%%], вашим самым сильным триггером, является ключевой.''',
    '''Чтобы добиться успеха, вы должны работать над тем, чтобы противостоять [%%], вашему самому мощному триггеру.''',
    '''Борьба с [%%], вашим самым значительным триггером, должна стать вашей главной целью.''',
    '''Работа с [%%] крайне необходима, поскольку это ваш самый мощный триггер.''',
    '''[%%] - это триггер, который имеет наибольшее влияние; на нем следует сосредоточиться.''',
    '''Ваш путь значительно выиграет, если вы обратитесь к [%%], вашему самому сильному триггеру.''',
    '''Триггер [%%] оказывает на вас наибольшее влияние, поэтому управление им имеет первостепенное значение.''',
    '''Для эффективного продвижения вперед вы должны сосредоточиться на [%%], вашем самом важном триггере.''',
    '''Управление [%%], вашим самым доминирующим триггером, является ключом к вашему успеху.''',
    '''В ваших усилиях концентрация на [%%], вашем самом существенном триггере, является жизненно важной.''',
    '''Работа с [%%] должна быть на первом месте в ваших усилиях, так как это ваш самый значительный триггер.''',
    '''[%%], ваш основной триггер, требует особого внимания для эффективного управления.''',
    '''Чтобы продвинуться вперед, решение проблемы [%%] имеет первостепенное значение, поскольку это ваш самый влиятельный триггер.''',
    '''Ваш путь к выздоровлению сосредоточен вокруг [%%], вашего самого мощного триггера.''',
    '''Управление [%%] крайне важно, так как это ваш самый мощный триггер.''',
    '''Очень важно сосредоточиться на [%%], триггере, который имеет наибольший вес.''',
    '''Для достижения успеха на вашем пути ключевым является решение проблемы [%%], вашего самого значимого триггера.''',
    '''Противостояние [%%] - это решающий шаг, поскольку это ваш самый влиятельный триггер.''',
    '''Решение проблемы [%%], вашего самого важного триггера, должно стать вашей главной целью.''',
    '''В вашем стремлении преодолеть зависимость [%%] - это триггер, который требует вашего самого пристального внимания.''',
    '''Управление [%%], вашим самым существенным триггером, является главным в вашем путешествии.''',
    '''Для достижения ваших целей необходимо сосредоточиться на [%%], вашем наиболее доминирующем триггере.''',
    '''Работа над [%%] имеет первостепенное значение, поскольку это ваш самый значимый триггер.''',
    '''Ваш успех зависит от работы над [%%] - триггером, оказывающим наиболее глубокое воздействие.''',
    '''[%%], ваш триггер первостепенной важности, требует от вас самоотверженных усилий для эффективного управления.''',
  ]
};

var nos = {
  'en': [
    '''You've come so far; don't give up now.''',
    '''Think about the reasons you started this journey.''',
    '''Remind yourself of the benefits of quitting.''',
    '''You have the strength to overcome this.''',
    '''Take it one day at a time. You can do it.''',
    '''Consider the positive changes in your health and life.''',
    '''Don't let a momentary setback define your progress.''',
    '''You've already shown resilience; keep pushing forward.''',
    '''Your future self will thank you for not giving up.''',
    '''Remember, quitting is a process, and setbacks happen.''',
    '''Seek support from friends and family; you're not alone.''',
    '''Don't let a temporary craving outweigh your long-term goals.''',
    '''It's okay to stumble, but it's not a reason to quit.''',
    '''Visualize the life you want without addiction.''',
    '''Reflect on the progress you've made so far.''',
    '''Stay focused on the positive changes ahead.''',
    '''Take a deep breath and believe in your ability to quit.''',
    '''Consider the people who believe in you and your journey.''',
    '''Setbacks are part of the journey; keep moving forward.''',
    '''Think about the self-respect that comes with quitting.''',
    '''One moment of weakness doesn't define your journey.''',
    '''You're stronger than any craving; keep going.''',
    '''Keep your eyes on the prize – a healthier life.''',
    '''Every effort you make is a step in the right direction.''',
    '''Think about the freedom that comes with quitting.''',
    '''Don't let a temporary urge control your future.''',
    '''Your journey is worth the effort; don't give up.''',
    '''Quitting is a journey with ups and downs; embrace it.''',
    '''You have the power to rewrite your story.''',
    '''Consider the loved ones who support your journey.''',
    '''One day at a time, one step at a time – you've got this.''',
    '''Keep reminding yourself of the reasons to quit.''',
    '''You're not alone in this; seek help and guidance.''',
    '''Every step you take is progress; don't lose sight of that.''',
    '''You're capable of overcoming this challenge.''',
    '''Quitting is a marathon, not a sprint; keep moving forward.''',
    '''Consider the possibilities and opportunities that await.''',
    '''Look back at how far you've come, and look forward to where you're going.''',
    '''Don't let a momentary craving rob you of your goals.''',
    '''You're writing a new, healthier chapter in your life.''',
    '''Keep believing in yourself and your journey.''',
    '''The toughest moments often lead to the greatest growth.''',
    '''You're in control of your choices and your future.''',
    '''Don't let a setback be the end of your journey.''',
    '''You have the strength within you to succeed.''',
    '''You're not alone; others have faced this journey too.''',
    '''Think about the life you envision for yourself without addiction.''',
    '''Every day you don't give in is a victory.''',
    '''Set a new goal for today and focus on achieving it.''',
    '''A relapse is a lesson, not a failure.''',
    '''Your journey is a testament to your resilience.''',
    '''The journey to quit is worth every effort.''',
    '''Keep your determination stronger than your cravings.''',
    '''Remind yourself of the positive changes you've experienced.''',
    '''You're not defined by your past mistakes; you're defined by your resilience.''',
    '''Think about the healthier, happier future ahead.''',
    '''Don't let temporary discomfort overshadow your long-term well-being.''',
    '''Remember the determination that led you to start this journey.''',
    '''Reflect on the support and love that surrounds you.''',
    '''Stay focused on the healthier, addiction-free life you desire.''',
    '''A relapse doesn't erase the progress you've made.''',
    '''Stay strong; you have the power to overcome addiction.''',
    '''Your journey is unique and worth every step.''',
    '''You've faced challenges before and emerged stronger.''',
    '''You're in control of your destiny; choose recovery.''',
    '''Remind yourself of the positive changes that come with quitting.''',
    '''You're not alone in this; reach out for support.''',
    '''Every day is a new opportunity to make progress.''',
    '''Your future self is cheering you on to keep going.''',
    '''A moment of craving doesn't define your entire journey.''',
    '''Consider the hope and possibilities that await you.''',
    '''Take a deep breath, find your inner strength, and continue your journey.''',
    '''Don't let a relapse become a permanent setback.''',
    '''Quitting is a courageous journey; you're on the right path.''',
    '''Remember the determination that led you to quit in the first place.''',
    '''Stay focused on your goals; they're within reach.''',
    '''You're capable of enduring these challenges and coming out stronger.''',
    '''Your journey is worth every effort; don't give up.''',
    '''Take one step at time, one day at a time; you're making progress."''',
    '''You're more resilient than you may realize.''',
    '''Consider the positive changes that quitting brings to your life.''',
    '''A setback doesn't define your journey; it's just a part of it.''',
    '''You're not alone; there's support and guidance available.''',
    '''Every moment of strength is a victory; keep counting them.''',
    '''You have the power to change your life for the better.''',
    '''Think about the freedom that comes with quitting addiction.''',
    '''Don't let temporary cravings derail your long-term goals.''',
    '''Your journey to quit is a path of self-discovery and growth.''',
    '''You're in control of your choices and your future.''',
    '''Stay focused on the healthier, happier future that awaits you.''',
    '''Consider the positive impact of quitting on your life and health.''',
    '''Reflect on the support and love you receive from those who care about you.''',
    '''You have the strength to overcome these challenges; keep going.''',
    '''Don't let a temporary craving diminish your long-term progress.''',
    '''Your determination is your greatest ally in this journey.''',
    '''Remember the reasons you chose to quit; they are still valid.''',
    '''You're not alone; seek help, support, and guidance.''',
    '''Every step you take is a step closer to a healthier life.''',
    '''You have the resilience and strength to overcome this challenge.''',
    '''Your journey to quit is a testament to your courage and determination.''',
    '''Your future self is cheering you on to keep going.''',
    '''Each craving is a test of your determination; pass it with flying colors.''',
    '''Your journey is unique, and that's what makes it special.''',
    '''You're not alone in this; seek help when you need it.''',
    '''Every day you overcome cravings is a step closer to freedom.''',
    '''Remind yourself of the positive changes that quitting brings to your life.''',
    '''You have the strength to rewrite your story and create a new beginning.''',
    '''Your journey is worth every effort; don't give up.''',
    '''You're not alone; others have faced similar challenges and overcome them.''',
    '''Think about the positive impact quitting will have on your health and well-being.''',
    '''One day at a time, one step at a time – you're making progress.''',
    '''Don't let cravings define your path; your determination does that.''',
    '''You're capable of enduring these challenges and emerging stronger.''',
    '''Your journey is a testament to your courage and resilience.''',
    '''The strength within you is greater than any craving.''',
    '''You're in control of your choices and your future.''',
    '''Don't let temporary discomfort overshadow your long-term well-being.''',
    '''You're a work in progress, and that's something to be proud of.''',
    '''Each step you take away from addiction is a step toward a healthier life.''',
    '''The path to recovery may have twists, but you have the power to navigate them.''',
    '''You're creating a life that's free from the burdens of addiction.''',
    '''Each day is an opportunity to make progress and build a better future.''',
    '''Remember the reasons that led you to start this journey.''',
    '''You're on a journey of self-discovery and personal growth.''',
    '''Stay strong, for your determination is your greatest asset.''',
    '''Your journey is marked by resilience and unwavering commitment.''',
    '''You're making progress with each step; keep moving forward.''',
    '''Stay focused on the healthier, happier future that awaits you.''',
    '''Quitting is a courageous decision, and you've already taken that step.''',
    '''Take it one step at a time; you're on the right path.''',
    '''You're more resilient and capable than you may realize.''',
    '''Your future self is counting on you to keep going.''',
    '''Every small victory is a step toward lasting change.''',
    '''You're not alone in this; there's support available to help you.''',
    '''Stay committed to your path, for it leads to a brighter future.''',
    '''You have the strength within you to rewrite your story.''',
    '''Think about the freedom and happiness that come with quitting addiction.''',
    '''Don't let temporary discomfort overshadow your long-term well-being.''',
    '''Your journey is a reflection of your courage and determination.''',
    '''You're building a life that's free from the chains of addiction.''',
    '''One moment of craving doesn't define your entire journey.''',
    '''Each day without addiction is a day of progress and personal growth.''',
    '''You're creating a future that's healthier, happier, and addiction-free.''',
    '''Stay strong and believe in your ability to overcome.''',
    '''Every effort you make is a step toward lasting change.''',
    '''Your journey is a testament to your strength and resilience.''',
    '''Don't let temporary cravings diminish your long-term progress.''',
    '''Your journey is worth every effort; don't give up.''',
    '''You're not alone; others have faced similar challenges and succeeded.''',
    '''Every craving you resist is a victory worth celebrating.''',
    '''Stay focused on the life you want to create for yourself.''',
    '''Every step you take away from addiction is a step toward a brighter future.''',
    '''Think about the positive impact quitting will have on your life and those around you.''',
    '''Your strength is greater than any craving. Keep pushing forward.''',
    '''Focus on the freedom and empowerment that comes with quitting.''',
    '''Setbacks are part of the journey, but they don't define your path.''',
    '''You've already overcome so much; don't stop now.''',
    '''Take it one moment at a time; you can overcome this challenge.''',
    '''Remember why you started this journey in the first place.''',
    '''Quitting is a process, and progress is made one step at a time.''',
    '''You're not alone; reach out for support when you need it.''',
    '''Visualize the healthier, addiction-free life that awaits you.''',
    '''You have the power to choose a life without addiction.''',
    '''Celebrate every small victory on your path to recovery.''',
    '''Each day is a new opportunity to move closer to your goals.''',
    '''Stay focused on the positive changes that come with quitting.''',
    '''Setbacks are temporary; your determination is permanent.''',
    '''You're building a future that's free from addiction – keep going.''',
    '''Take a deep breath and trust in your ability to overcome.''',
    '''Seek support from those who care about your well-being.''',
    '''Don't let cravings overshadow your long-term vision.''',
    '''You're rewriting your story, and it's one of resilience and strength.''',
    '''Stay patient with yourself; recovery is a journey.''',
    '''Consider the happiness and health that come with quitting.''',
    '''You've got the courage to face and conquer this challenge.''',
    '''You're not defined by your past but by your determination to change.''',
    '''Every effort you make brings you closer to your goals.''',
    '''Believe in your ability to create a brighter future.''',
    '''Think about the people who believe in your journey and support you.''',
    '''You're a work in progress, and every step matters.''',
    '''Stay committed to the path that leads to a healthier life.''',
    '''Your journey is a testament to your strength and resilience.''',
    '''The path to recovery may have obstacles, but you have the power to overcome them.''',
    '''Keep your vision clear, and your determination strong.''',
    '''Every step you take is progress, no matter how small.''',
    '''You're on a journey of self-discovery and positive change.''',
    '''Remember, quitting is a courageous choice.''',
    '''Each craving you resist is a victory worth celebrating.''',
    '''The journey may be challenging, but it's worth every step.''',
    '''Your commitment to change is an inspiration to others.''',
    '''Visualize a future where addiction no longer holds you back.''',
    '''You have the strength to overcome this challenge; keep going.''',
    '''Each day without addiction is a day of personal growth.''',
    '''Stay focused on the life you want to create for yourself.''',
    '''Your journey is marked by resilience and determination.''',
    '''Your progress is measured by your determination to keep moving forward.''',
    '''Don't let temporary cravings diminish your long-term progress.''',
    '''You're not alone; reach out for the support and guidance you need.''',
    '''The journey may have bumps, but each one leads you closer to your goals.''',
    '''Stay focused on the healthier, addiction-free life you desire.''',
  ],
  'ru': [
    '''Вы прошли такой долгий путь; не сдавайтесь.''',
    '''Подумайте о причинах, побудивших вас начать этот путь.''',
    '''Напомните себе о преимуществах отказа от курения.''',
    '''У Вас есть силы, чтобы преодолеть это.''',
    '''Принимайте все как один день за один раз. Вы можете это сделать.''',
    '''Подумайте о положительных изменениях в своем здоровье и жизни.''',
    '''Не позволяйте сиюминутным неудачам определять ваш прогресс.''',
    '''Вы уже проявили стойкость, продолжайте двигаться вперед.''',
    '''Ваше будущее будет благодарить Вас за то, что Вы не сдались.''',
    '''Помните, что отказ от курения - это процесс, и неудачи случаются.''',
    '''Обратитесь за поддержкой к друзьям и близким - вы не одиноки.''',
    '''Не позволяйте временному желанию перевесить ваши долгосрочные цели.''',
    '''Оступиться - это нормально, но это не повод бросать.''',
    '''Представьте себе жизнь без зависимости.''',
    '''Подумайте о том, чего вы уже добились.''',
    '''Сосредоточьтесь на предстоящих позитивных изменениях.''',
    '''Сделайте глубокий вдох и поверьте в свою способность бросить.''',
    '''Подумайте о людях, которые верят в вас и ваш путь.''',
    '''Неудачи - это часть пути; продолжайте двигаться вперед.''',
    '''Подумайте о самоуважении, которое приходит с отказом от курения.''',
    '''Один момент слабости не определяет ваш путь.''',
    '''Вы сильнее любой тяги; продолжайте идти вперед.''',
    '''Следите за призом - здоровой жизнью.''',
    '''Каждое ваше усилие - это шаг в правильном направлении.''',
    '''Подумайте о свободе, которая приходит с отказом от курения.''',
    '''Не позволяйте временному желанию управлять вашим будущим.''',
    '''Ваш путь стоит усилий, не сдавайтесь.''',
    '''Отказ от курения - это путь со взлетами и падениями; примите его.''',
    '''В ваших силах переписать свою историю.''',
    '''Подумайте о близких, которые поддерживают ваш путь.''',
    '''Один день за раз, один шаг за раз - у вас все получится.''',
    '''Постоянно напоминайте себе о причинах отказа от курения.''',
    '''Вы не одиноки в этом; обратитесь за помощью и советом.''',
    '''Каждый Ваш шаг - это прогресс, не забывайте об этом.''',
    '''Вы способны преодолеть это испытание.''',
    '''Отказ от курения - это марафон, а не спринт; продолжайте двигаться вперед.''',
    '''Подумайте о том, какие возможности открываются перед вами.''',
    '''Оглянитесь на пройденный путь и посмотрите вперед.''',
    '''Не позволяйте сиюминутным желаниям лишить вас цели.''',
    '''Вы пишете новую, более здоровую главу в своей жизни.''',
    '''Продолжайте верить в себя и в свой путь.''',
    '''Самые трудные моменты часто приводят к наибольшему росту.''',
    '''Вы контролируете свой выбор и свое будущее.''',
    '''Не позволяйте неудачам стать концом вашего пути.''',
    '''У вас есть силы, чтобы добиться успеха.''',
    '''Вы не одиноки, другие тоже проходили этот путь.''',
    '''Подумайте о том, какой вы представляете себе жизнь без зависимости.''',
    '''Каждый день, когда вы не сдаетесь, - это уже победа.''',
    '''Поставьте себе новую цель на сегодня и сосредоточьтесь на ее достижении.''',
    '''Рецидив - это урок, а не поражение.''',
    '''Ваш путь - это свидетельство вашей стойкости.''',
    '''Путь к отказу от курения стоит любых усилий.''',
    '''Пусть ваша решимость будет сильнее тяги.''',
    '''Напоминайте себе о позитивных изменениях, которые вы пережили.''',
    '''Вас определяют не прошлые ошибки, а ваша стойкость.''',
    '''Думайте о том, что впереди вас ждет более здоровое и счастливое будущее.''',
    '''Не позволяйте временному дискомфорту затмить ваше долгосрочное благополучие.''',
    '''Помните о решимости, которая привела вас на этот путь.''',
    '''Размышляйте о поддержке и любви, которые вас окружают.''',
    '''Сосредоточьтесь на здоровой жизни без зависимости, к которой вы стремитесь.''',
    '''Рецидив не перечеркнет достигнутый прогресс.''',
    '''Оставайтесь сильными; у вас есть силы преодолеть зависимость.''',
    '''Ваш путь уникален и стоит каждого шага.''',
    '''Вы уже сталкивались с трудностями и стали сильнее.''',
    '''Вы контролируете свою судьбу; выберите выздоровление.''',
    '''Напоминайте себе о положительных изменениях, которые происходят после отказа от курения.''',
    '''Вы не одиноки в этом; обратитесь за поддержкой.''',
    '''Каждый день - это новая возможность добиться прогресса.''',
    '''Ваше будущее "я" поддерживает вас, чтобы вы не останавливались на достигнутом.''',
    '''Минутная тяга не определяет весь Ваш путь.''',
    '''Подумайте о надежде и возможностях, которые ждут вас впереди.''',
    '''Сделайте глубокий вдох, найдите в себе силы и продолжайте свой путь.''',
    '''Не позволяйте рецидиву стать постоянной неудачей.''',
    '''Отказ от курения - это мужественный путь, и вы на правильном пути.''',
    '''Помните о решимости, которая привела вас к отказу от курения в самом начале.''',
    '''Сосредоточьтесь на своих целях - они достижимы.''',
    '''Вы способны пройти через эти испытания и стать сильнее.''',
    '''Ваш путь стоит всех усилий, не сдавайтесь.''',
    '''Делайте один шаг за другим, один день за другим; вы делаете успехи".''',
    '''Вы более устойчивы, чем можете себе представить.''',
    '''Подумайте о положительных изменениях, которые принесет в вашу жизнь отказ от курения.''',
    '''Неудачи не определяют ваш путь, это лишь его часть.''',
    '''Вы не одиноки, вас всегда поддержат и подскажут.''',
    '''Каждый момент силы - это победа; продолжайте считать их.''',
    '''Вы в силах изменить свою жизнь к лучшему.''',
    '''Подумайте о свободе, которая приходит с отказом от зависимости.''',
    '''Не позволяйте временным желаниям сорвать достижение долгосрочных целей.''',
    '''Ваш путь к отказу от курения - это путь самопознания и роста.''',
    '''Вы контролируете свой выбор и свое будущее.''',
    '''Сосредоточьтесь на здоровом и счастливом будущем, которое вас ждет.''',
    '''Подумайте о положительном влиянии отказа от курения на Вашу жизнь и здоровье.''',
    '''Подумайте о поддержке и любви, которую Вы получаете от тех, кто заботится о Вас.''',
    '''У вас есть силы преодолеть эти трудности; продолжайте идти вперед.''',
    '''Не позволяйте временной тяге ослабить ваш долгосрочный прогресс.''',
    '''Ваша решимость - ваш главный союзник на этом пути.''',
    '''Помните о причинах, по которым Вы решили бросить курить, они по-прежнему актуальны.''',
    '''Вы не одиноки; обращайтесь за помощью, поддержкой и руководством.''',
    '''Каждый ваш шаг - это шаг к здоровому образу жизни.''',
    '''У Вас есть силы и стойкость, чтобы преодолеть это испытание.''',
    '''Ваш путь к отказу от курения - это свидетельство вашего мужества и решимости.''',
    '''Ваше будущее "я" подбадривает Вас, чтобы Вы не останавливались на достигнутом.''',
    '''Каждое желание - это проверка вашей решимости; пройдите ее с блеском.''',
    '''Ваш путь уникален, и именно это делает его особенным.''',
    '''Вы не одиноки в этом; обращайтесь за помощью, если она вам нужна.''',
    '''Каждый день преодоления тяги - это шаг к свободе.''',
    '''Напоминайте себе о положительных изменениях, которые принесет в вашу жизнь отказ от курения.''',
    '''У вас есть силы, чтобы переписать свою историю и начать новую.''',
    '''Ваш путь стоит всех усилий; не сдавайтесь.''',
    '''Вы не одиноки: другие сталкивались с подобными проблемами и преодолевали их.''',
    '''Подумайте о том, что отказ от курения положительно скажется на Вашем здоровье и самочувствии.''',
    '''Один день за другим, один шаг за другим - вы делаете успехи.''',
    '''Не позволяйте тяге определять ваш путь - это сделает ваша решимость.''',
    '''Вы способны преодолеть эти трудности и стать сильнее.''',
    '''Ваш путь - это свидетельство вашего мужества и стойкости.''',
    '''Сила, заключенная в Вас, сильнее любой тяги.''',
    '''Вы контролируете свой выбор и свое будущее.''',
    '''Не позволяйте временному дискомфорту затмить ваше долгосрочное благополучие.''',
    '''Вы находитесь в процессе работы, и этим можно гордиться.''',
    '''Каждый шаг, сделанный вами в сторону от зависимости, - это шаг к здоровой жизни.''',
    '''На пути к выздоровлению могут быть повороты, но у вас есть возможность их преодолевать.''',
    '''Вы создаете свою жизнь, свободную от бремени зависимости.''',
    '''Каждый день - это возможность добиться прогресса и построить лучшее будущее.''',
    '''Помните о причинах, побудивших вас начать этот путь.''',
    '''Вы находитесь на пути самопознания и личностного роста.''',
    '''Не падайте духом, ведь ваша решимость - это ваше главное достоинство.''',
    '''Ваш путь отмечен стойкостью и непоколебимой целеустремленностью.''',
    '''С каждым шагом вы добиваетесь прогресса; продолжайте двигаться вперед.''',
    '''Сосредоточьтесь на здоровом и счастливом будущем, которое вас ждет.''',
    '''Отказ от курения - это мужественное решение, и Вы уже сделали этот шаг.''',
    '''Делайте шаг за шагом - вы на правильном пути.''',
    '''Вы более выносливы и способны, чем можете себе представить.''',
    '''Ваше будущее "я" рассчитывает на то, что вы не остановитесь на достигнутом.''',
    '''Каждая маленькая победа - это шаг к долгосрочным изменениям.''',
    '''Вы не одиноки в этом; вам всегда помогут.''',
    '''Оставайтесь верными своему пути, ведь он ведет к светлому будущему.''',
    '''У вас есть силы, чтобы переписать свою историю.''',
    '''Подумайте о свободе и счастье, которые приходят с отказом от зависимости.''',
    '''Не позволяйте временному дискомфорту затмить ваше долгосрочное благополучие.''',
    '''Ваш путь - это отражение вашего мужества и решимости.''',
    '''Вы строите жизнь, свободную от оков зависимости.''',
    '''Один момент тяги не определяет весь ваш путь.''',
    '''Каждый день без зависимости - это день прогресса и личностного роста.''',
    '''Вы создаете будущее, которое будет более здоровым, счастливым и свободным от зависимости.''',
    '''Оставайтесь сильными и верьте в свою способность преодолеть трудности.''',
    '''Каждое ваше усилие - это шаг к долгосрочным изменениям.''',
    '''Ваш путь - это свидетельство вашей силы и стойкости.''',
    '''Не позволяйте временному влечению ослаблять ваш долгосрочный прогресс.''',
    '''Ваш путь стоит всех усилий; не сдавайтесь.''',
    '''Вы не одиноки; другие люди сталкивались с подобными проблемами и добились успеха.''',
    '''Каждое желание, которое вы преодолеваете, - это победа, которую стоит отпраздновать.''',
    '''Сосредоточьтесь на той жизни, которую вы хотите создать для себя.''',
    '''Каждый шаг, сделанный вами в сторону от зависимости, - это шаг к светлому будущему.''',
    '''Подумайте о том, какое положительное влияние окажет отказ от наркотиков на вашу жизнь и жизнь окружающих вас людей.''',
    '''Ваша сила сильнее любой тяги. Продолжайте двигаться вперед.''',
    '''Сосредоточьтесь на свободе и силе, которые приходят с отказом от курения.''',
    '''Неудачи - это часть пути, но они не определяют ваш путь.''',
    '''Вы уже многое преодолели, не останавливайтесь сейчас.''',
    '''Не останавливайтесь сейчас. Возьмите один момент за один раз; вы сможете преодолеть это испытание.''',
    '''Помните, зачем вы вообще начали этот путь.''',
    '''Отказ от курения - это процесс, а прогресс достигается шаг за шагом.''',
    '''Вы не одиноки; обращайтесь за поддержкой, если она вам нужна.''',
    '''Визуализируйте более здоровую и свободную от зависимости жизнь, которая вас ждет.''',
    '''В ваших силах выбрать жизнь без зависимости.''',
    '''Отмечайте каждую маленькую победу на пути к выздоровлению.''',
    '''Каждый день - это новая возможность приблизиться к своим целям.''',
    '''Сосредоточьтесь на позитивных изменениях, которые происходят с отказом от курения.''',
    '''Неудачи временны, а ваша решимость постоянна.''',
    '''Вы строите будущее, свободное от зависимости, - не останавливайтесь на достигнутом.''',
    '''Сделайте глубокий вдох и поверьте в свою способность преодолеть трудности.''',
    '''Обращайтесь за поддержкой к тем, кому небезразлично ваше благополучие.''',
    '''Не позволяйте тяге к наркотикам затмить ваше долгосрочное видение.''',
    '''Вы пишете свою историю, и это история стойкости и силы.''',
    '''Будьте терпеливы к себе: выздоровление - это путь.''',
    '''Подумайте о счастье и здоровье, которые приходят с отказом от курения.''',
    '''У Вас есть мужество, чтобы принять и преодолеть этот вызов.''',
    '''Вас определяет не ваше прошлое, а ваша решимость измениться.''',
    '''Каждое ваше усилие приближает вас к цели.''',
    '''Верьте в свою способность создать светлое будущее.''',
    '''Подумайте о людях, которые верят в ваш путь и поддерживают вас.''',
    '''Вы находитесь в процессе работы, и каждый шаг имеет значение.''',
    '''Сохраняйте приверженность пути, ведущему к здоровой жизни.''',
    '''Ваш путь - это свидетельство вашей силы и стойкости.''',
    '''На пути к выздоровлению могут возникнуть препятствия, но у вас есть силы их преодолеть.''',
    '''Сохраняйте ясность видения и решимость.''',
    '''Каждый ваш шаг - это прогресс, каким бы маленьким он ни был.''',
    '''Вы находитесь на пути самопознания и позитивных перемен.''',
    '''Помните, что отказ от курения - это мужественный выбор.''',
    '''Каждый раз, когда вы сопротивляетесь тяге, - это победа, которую стоит отпраздновать.''',
    '''Путь может быть трудным, но каждый шаг стоит того.''',
    '''Ваше стремление к переменам вдохновляет других.''',
    '''Представьте себе будущее, в котором зависимость больше не будет удерживать вас.''',
    '''У вас есть силы преодолеть это испытание; продолжайте идти вперед.''',
    '''Каждый день без зависимости - это день личностного роста.''',
    '''Сосредоточьтесь на той жизни, которую вы хотите создать для себя.''',
    '''Ваш путь отмечен стойкостью и решимостью.''',
    '''Ваш прогресс измеряется вашей решимостью продолжать двигаться вперед.''',
    '''Не позволяйте временной тяге к наркотикам свести на нет ваш долгосрочный прогресс.''',
    '''Вы не одиноки; обращайтесь за поддержкой и советом, в которых вы нуждаетесь.''',
    '''На этом пути могут встречаться неровности, но каждая из них приближает вас к цели.''',
    '''Сосредоточьтесь на здоровой жизни без зависимости, к которой вы стремитесь.''',
  ]
};
